cloud:
  aws:
    credentials:
      access-key: AKIAX2V2QPTNTMBNASS3
      secret-key: 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
    region:
      static: eu-west-2
    stack:
      auto: false

application:
  bucket:
    name: student-report-bucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB